name: gh-pages

on:
  push:
    branches:
      - master
    paths:
      - /packages/docs/**

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci
        working-directory: docs

      - name: Generate
        run: npm run generate
        working-directory: docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/docs/dist
