name: e2e-tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Init docker
        run: docker-compose up -d

      - run: npm install
        working-directory: ./src/backend
      - run: npm run test:e2e
        working-directory: ./src/backend
