name: tests

on:
  push:
    paths:
      - packages/server/**
  pull_request:
    paths:
      - packages/server/**

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Init docker
        run: docker-compose up -d

      - run: npm install
        working-directory: packages/server

      - run: npm run test:e2e
        working-directory: packages/server
        env:
          PAYPAL_CLIENT_ID: ${{ secrets.PAYPAL_CLIENT_ID }}
          PAYPAL_SECRET_KEY: ${{ secrets.PAYPAL_SECRET_KEY }}

      - name: Codecov
        uses: codecov/codecov-action@v1
        with:
          directory: packages/server/coverage
